-- Generated by the database client.
CREATE TABLE items(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time date,
    name varchar(254),
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE inventory(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time date,
    item_id integer,
    quantity integer,
    PRIMARY KEY(id),
    CONSTRAINT inventory_item_id_fkey FOREIGN key(item_id) REFERENCES items(id)
);